version: '3'
services:
  postgres:
    build: .
    environment:
      - POSTGRES_USER=webappbase
      - POSTGRES_PASSWORD=webappbase
    ports:
      - 15415:5432
    volumes:
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
      - ./backup:/backup
